import {readdir, readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const docsDirectory = resolve(here, '../../docs');
const output = resolve(here, '../src/docs.generated.js');
const files = (await readdir(docsDirectory)).filter((file) => file.endsWith('.mdx')).sort();

const documents = [];
let indexedFiles = 0;
for (const file of files) {
  const raw = await readFile(resolve(docsDirectory, file), 'utf8');
  if (/^excludeFromAI:\s*true$/m.test(raw)) continue;
  indexedFiles += 1;
  const title = raw.match(/^title:\s*(.+)$/m)?.[1]?.trim() || file.replace(/\.mdx$/, '');
  const body = raw.replace(/^---[\s\S]*?---\s*/, '');
  const parts = body.split(/(?=^##?\s+)/m).filter((part) => part.trim());

  for (const part of parts) {
    const heading = part.match(/^#{1,2}\s+(.+)$/m)?.[1]?.trim() || title;
    const content = part
      .replace(/<[^>]+>/g, ' ')
      .replace(/\{[^}]+\}/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    if (content) {
      documents.push({
        page: file.replace(/\.mdx$/, ''),
        title,
        heading,
        content,
      });
    }
  }
}

await writeFile(
  output,
  `// Generated by scripts/build-context.mjs. Do not edit.\nexport const DOCUMENTS = ${JSON.stringify(documents, null, 2)};\n`,
);

console.log(`Indexed ${documents.length} sections from ${indexedFiles} documentation pages.`);
