require("hyprlua.env")
require("monitors")
require("hyprlua.binds")
require("hyprlua.general")
require("hyprlua.decoration")
require("hyprlua.exec")
require("hyprlua.workspace")
require("hyprlua.windowrule")
require("colors")
require("hyprlua.input")
require("hyprlua.layout")
require("hyprlua.animations")
require("hyprlua.plugins")

hl.env("HYPRCURSOR_THEME", "Moga")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("XCURSOR_THEME", "Moga")
hl.env("XCURSOR_SIZE", "24")

