color0 #3f4948
color1 #ffb4ab
color2 #90d2cf
color3 #b2ccca
color4 #d5bcf2
color5 #90d2cf
color6 #b2ccca
color7 #e1e3e2
color8 #899392
color9 #ffb4ab
color10 #90d2cf
color11 #b2ccca
color12 #d5bcf2
color13 #90d2cf
color14 #b2ccca
color15 #e1e3e2

cursor                #e1e3e2
cursor_text_color     #111414
background            #111414
foreground            #e1e3e2
selection_foreground  #bec8c7
selection_background  #3f4948
active_border_color   #90d2cf
inactive_border_color #3f4948
url_color             #90d2cf

active_tab_foreground   #003736
active_tab_background   #90d2cf
inactive_tab_foreground #bec8c7
inactive_tab_background #3f4948
cursor_trail_color      #bec8c7
