hl.on("hyprland.start", function () 
  hl.exec_cmd("waypaper --restore")
  hl.exec_cmd("syncthing --no-browser")
  hl.exec_cmd("quickshell -p ~/.local/src/HyprDots/tide-island/")
  hl.exec_cmd("systemctl --user start dunst")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("wl-paste --type text --watch cliphist store # Stores only text data")
  hl.exec_cmd("wl-paste --type image --watch cliphist store # Stores only text data")
end)